name: Check compile, tests & KDocs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 3.0.0-dev # This will be moved to master once released
    paths:
      - 'pom.xml'
      - 'src/main/**.java'
      - 'src/test/**.java'
      - 'src/main/**.kt'
      - 'src/test/**.kt'
  push:
    branches: 
      - 3.0.0-dev
    paths: 
      - 'pom.xml'
      - 'src/main/**.java'
      - 'src/test/**.java'
      - 'src/main/**.kt'
      - 'src/test/**.kt'
jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Compile and run tests with Maven
        run: mvn -B --file pom.xml test
  check-kdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build KDocs with Maven
        run: mvn -P docs -B BotCommandsBuild:generate-version-info dokka:dokka --file pom.xml
